version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin  
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgress_data:/var/lib/postgresql/data

volumes:   # ✅ must be outside "services"
  postgress_data:
